spring.application.name: spring-boot-sonar
management.endpoints.web.exposure.include: '*'

# H2 Database
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings.web-allow-others: true
      settings.trace: false
  datasource:
    url: jdbc:h2:tcp://localhost/testdb;SCHEMA=PUBLIC
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa: 
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
